package com.github.oliverpavey.siteindex;

import com.github.oliverpavey.siteindex.scanner.SiteScanner;
import com.github.oliverpavey.siteindex.testutils.TestsiteServer;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.thymeleaf.TemplateEngine;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

@Slf4j
@ActiveProfiles("test")
@SpringBootTest
class SiteindexAutorunTest {

    @Autowired
    SiteScanner siteScanner;

    @Autowired
    TemplateEngine templateEngine;

    /**
     * Execute the scan against the tests website, and process the model through Thymeleaf,
     * checking that the response looks like an XHTML document.
     *
     * @throws IOException The runScanner method "throws IOException" so we throw it here too.
     */
    @Test
    void scanAndGenerateTemplateTest() throws IOException {

        try (final TestsiteServer server = new TestsiteServer()) {
            final String baseUrl = server.getBaseUrl();
            final String homepageUrl = baseUrl + "index.html";

            final SiteindexAutorun siteindexAutorun = new SiteindexAutorun(siteScanner, templateEngine);
            final String xhtml = siteindexAutorun.runScanner(homepageUrl, null);
            log.debug("{}", xhtml);

            assertNotNull(xhtml, "XHTML returned is null");
            assertNotEquals(0, xhtml.length(), "XHTML returned is empty");
            assertTrue(xhtml.startsWith("<!DOCTYPE html>"), "XHTML not generated by template");
        }
    }
}